package com.parpet.customer_management.exception;

public enum ERROR_CODE {
    UNCLASSIFIED_ERROR,
    JSON_PARSE_ERROR,
    ILLEGAL_ARGUMENT_ERROR,
    ILLEGAL_STATE_EXCEPTION,
    ENTITY_OBJECT_NOT_FOUND,
    NO_SUCH_ELEMENT,
    ENTITY_NOT_FOUND
}
